import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const suisse = localFont({
  src: [
    {
      path: "../../public/fonts/SuisseIntlTrial-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/SuisseIntlTrial-RegularIt.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/SuisseIntlTrial-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/SuisseIntlTrial-MediumIt.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../../public/fonts/SuisseIntlTrial-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/SuisseIntlTrial-BoldIt.otf",
      weight: "700",
      style: "italic",
    },
  ],
  preload: true,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${suisse.className} overflow-x-hidden`}>
        <NuqsAdapter>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main>
              <Header />
              {children}
            </main>
          </ThemeProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
